services:
    smartersolutions.ezimagecrop.filter.gravity_loader:
        class: SmarterSolutions\EzComponents\EzImageCropBundle\Imagine\Filter\Loader\ThumbnailGravityCenterFilterLoader
        public: false
        tags:
            - { name: liip_imagine.filter.loader, loader: "gravity/center" }
